### ISSUE TITLE
GPS Data to Store

### ISSUE THREAD

**Issue by facundofor** [bradleynbaker/PathOne-Mobile-Tracking-Android#2]
GPS Data
The System should handle the following time-position-velocity report GPS Data (TPV)
(source http://catb.org/gpsd/gpsd_json.html)
- [ ] Fix Quality (aka Mode) In Android this is Provider
- [ ] Fix Time
- [ ] Lat
- [ ] Lon
- [ ] Speed
- [ ] Heading (aka Track)
- [ ] Altitude
- [ ] One sigma estimated position error (EPE) - In Android is Accuracy

**Comment by martinpb** [comment]
Currently Lat / Long is stored in DB. Updating with rest of the databases.
