### ISSUE TITLE
Data logging

### ISSUE THREAD

**Issue by facundofor** [bradleynbaker/PathOne-Mobile-Tracking-Android#3]
The as long as Tracking is Enabled, the app will store GPS positions (or best quality Location) based on configuration.

The GPS Log should be stored in a local Database. The data will be sent to the server according to another issue (Data Log Auto download)
Some considerations:
we should be able to do 1hz (1 location per second)
store at least 96 hrs of continuous recording
Autodelete positions older than 6 month

**Comment by martinpb** [comment]
Current version stores positions on local database.
