### ISSUE TITLE
Live Tracking Report

### ISSUE THREAD

**Issue by facundofor** [bradleynbaker/PathOne-Mobile-Tracking-Android#5]
Settings
Minimum report timeframe
The minimum elapsed time before trying to send a location to the Server. This is specified per channel. (Wi-Fi or Cell)

Maximum report timeframe
The maximum elapsed time before trying to send a location to the Server. This is specified per channel. (Wi-Fi or Cell)

There will NOT be a retry mechanism in Live tracking. If the transmission fails, we will "wait" until the next time we get a position.

**Comment by martinpb** [comment]
As this is a settings related task. Wont make sense to implement the settings get-from-server functionality first? Settings will apply to a number of other pieces. (note: setting will be implemented per user)
