### ISSUE TITLE
Data Log Auto download

### ISSUE THREAD

**Issue by facundofor** [bradleynbaker/PathOne-Mobile-Tracking-Android#6]
The system should be able to download (send to server) positions automatically whenever is within range of a known Wi-Fi hotspot.

The data will be transmitted in batches of 20 positions per API call. The return will be error or a Batch number. The DB records that were sent will be updated with the Batch Number.

Data will NOT be deleted from the DB, there will be another process (outlined in a different Issue) that will take care of that.

**Comment by facundofor** [comment]
JSON Payload:

{   "time": ,
  "longitude":    ,
  "latitude":  ,
  “altitude”: ,
  “speed": ,
  “heading”: ,
  “accuracy”: ,
  “quality”:                   (provider in Android)
}
]

**Comment by martinpb** [comment]
NOTE: 

Today report batch id is as follows: 

report_batch_id":"515258772-1481118478"

Will set string data type in android db storage for batch id.

**Comment by martinpb** [comment]
Web api need to be updated. Server response seems to be just OK right now. should need to be batch id.

**Comment by martinpb** [comment]
We need to define how we will set valid ssid names.

**Comment by martinpb** [comment]
Commited to master. SSID name detection works although commented until we define how we will set valid names.
